### ISSUE TITLE
Gravity for windows

### ISSUE THREAD

**Issue by nitashasahani** [coin-or/Gravity#39]
I tried installing Gravity for Windows 10 and I am facing issues as it cannot find some library functions, can you help me with that?

**Comment by hhijazi** [comment]
Which solver are you trying to use?

**Comment by nitashasahani** [comment]
I am trying to use C++ solver. I have visual studio. 

Do I need to have Cplex or Gurobi for this?

**Comment by hhijazi** [comment]
You do not need to have Cplex or Gurobi. What is the error you are getting? You can copy paste the log here.

**Comment by nitashasahani** [comment]
Hello

Sorry for the late reply.
I have attached the error log file.

Thank you
Nitasha Sahani

**Comment by hhijazi** [comment]
I don't see the attachment.

**Comment by nitashasahani** [comment]
please check this

**Comment by hhijazi** [comment]
still nothing, just copy paste the log here.

**Comment by tkralphs** [comment]
@nitashasahani you're probably replying by e-mail and attaching a file to the e-mail, but I don't think this works. The attachment get stripped. You have to attach the file to the issue through the browser interface by drag and drop.

https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

In general, it's much easier to work with issues through the browser interface.

**Comment by nitashasahani** [comment]
![error file](https://user-images.githubusercontent.com/49203108/55523340-af50e000-5656-11e9-862b-501d21d209cc.JPG)
 
I hope this works

**Comment by hhijazi** [comment]
This works, I will look into this and get back to you.

**Comment by hhijazi** [comment]
Ok, I fixed a few compatibility issues and I was able to successfully compile the gravity_test solution (using visual studio 19 and Cmake 3.14.1). I will try to fix the other solutions later on.

**Comment by hhijazi** [comment]
Sorry it took a bit long :) I have now added a set of instructions to compile Gravity with IPOP/HSL on Windows here: https://github.com/coin-or/Gravity/blob/master/INSTALL.md
I also added a GitHub actions workflow for Windows here: https://github.com/coin-or/Gravity/actions
