### ISSUE TITLE
link error when issuing make

### ISSUE THREAD

**Issue by zhangshixuanus** [coin-or/Gravity#40]
Hi,
I am trying to install Gravity on Linux. Following the instructions in INSTALL.md, when I issue the last command `make -j4` I found some linking error during the make process.
`[ 77%] Linking CXX executable ../../bin/Release/acuc
/lib/../lib64/crt1.o: In function '_start':`
`(.text+0x20): undefined reference to 'main'`
`collect2: error: ld returned 1 exit status`
`make[2]: *** [examples/CMakeFiles/acuc.dir/build.make:162: ../bin/Release/acuc] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:487: examples/CMakeFiles/acuc.dir/all] Error 2`
`make: *** [Makefile:84: all] Error 2`
The compiler version is GCC 7.3.1 and the CMake version is 3.13. In the cmake configuration, two solvers (Gurobi and Ipopt) are enabled successfully. Could you please look into this error? Thank you very much.

**Comment by hhijazi** [comment]
Hi, 
This was caused by a recent commit, I recommend using the stable version of Gravity: https://github.com/coin-or/Gravity/releases/tag/v1.0.8
Or switch to the Complex branch: git checkout Complex.
@guanglei1wang can you revert to the commit where acuc does not cause a compile issue on the master branch?

**Comment by hhijazi** [comment]
I just update the master branch to exclude the acuc executable, everything should compile fine now, you can do git pull and let me know if you still have issues.

**Comment by hhijazi** [comment]
This seems to be fixed.

**Comment by zhangshixuanus** [comment]
The error is fixed. Thank you very much.
