### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by dexterurbane** [coin-or/Gravity#79]
The following short program fails with: `libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: No derivatives stored!`.

Background: I've implemented OPF for unbalanced networks but was getting this crash. I was able to still cause the error with the greatly simplified program below. It may be possible to further reduce its complexity.

```
#define USE_IPOPT

#include <iostream>

#include <gravity/model.h>
#include <gravity/solver.h>
#include <SgtCore/Common.h>

int main()
{
    using namespace gravity;
    using namespace std;

    Model<> mod;

    var<double> t1("t1", -1.0, 1.0); mod.add_var(t1); t1.initialize_all(0.0);
    var<double> t2("t2", -1.0, 1.0); mod.add_var(t2); t2.initialize_all(0.0);
    var<double> p("p", -1.0, 1.0); mod.add_var(p); p.initialize_all(0.0);

    Constraint<double> c1("c1");
    c1 += p - cos(t1 - t2);
    c1 == 0.0;
    mod.add_constraint(c1);
   
    Constraint<double> c2("c2");
    c2 += p - sin(t1 - t2);
    c2 == 0.0;
    mod.add_constraint(c2);
    
    mod.min(p);

    mod.print();

    solver<> s(mod, ipopt);
    s.run();
    
    mod.print();
}
```

**Comment by dexterurbane** [comment]
Simplified version that still crashes:

```
#define USE_IPOPT

#include <iostream>

#include <gravity/model.h>
#include <gravity/solver.h>
#include <SgtCore/Common.h>

int main()
{
    using namespace gravity;
    using namespace std;

    Model<> mod;

    var<double> t1("t1", -1.0, 1.0); mod.add_var(t1); t1.initialize_all(0.0);
    var<double> t2("t2", -1.0, 1.0); mod.add_var(t2); t2.initialize_all(0.0);

    Constraint<double> c1("c1");
    c1 += cos(t1 - t2);
    c1 == 0.0;
    mod.add_constraint(c1);
   
    Constraint<double> c2("c2");
    c2 += sin(t1 - t2);
    c2 == 0.0;
    mod.add_constraint(c2);
    
    mod.min(t1 + t2);

    mod.print();

    solver<> s(mod, ipopt);
    s.run();
    
    mod.print();
}
```

**Comment by kaarthiksundar** [comment]
Try adding a return 0 at the end of the main function

**Comment by dexterurbane** [comment]
Afraid that's not it - main will always return 0 if it reaches the end of control. The exception is thrown at line 971 of func.h:
https://github.com/coin-or/Gravity/blob/master/include/gravity/func.h#L971

My compile command, on macOS: `clang++ -std=c++14 -w -o test_gravity -lgravity -lipopt test_gravity.cc`

**Comment by dexterurbane** [comment]
I think the problem originates when the constraints and their derivatives are `embed`ded in the model - possibly something to do with the fact that the expressions are stored in a map by their `to_str()` value, possibly something to do with the treatment of the negative sign as I'm seeing keys like `-cos(t1 - t2)` going into `_nl_funcs_map` in `model.h`. But this is all just a hunch, at present.

**Comment by hhijazi** [comment]
Hi @dexterurbane! Just saw this issue! Will have a look asap. I do have a working unbalanced OPF implementation here: https://github.com/lanl-ansi/ODO

**Comment by dexterurbane** [comment]
Hi @hhijazi, hope you and the family are well! Cheers for this. RE some of my comments above: I don't think it's anything to do with the keys or unary minus anymore. It seems that gravity tries to look up the derivative of a function that maps to a function that was created as the second derivative of another function, which doesn't have stored derivatives (possibly because only first and second derivatives are stored). Or something like that - I don't have a great understanding of the code!

**Comment by hhijazi** [comment]
I just fixed it, the example you provided is now part of gravity_test.cpp, thanks for the catch!
We're doing ok, hanging tight during these crazy times, hope you're all good too!
Really nice to hear from you. Do not hesitate to ping me via email if you need any help with Gravity.

**Comment by hhijazi** [comment]
Fixed in commit 6ebc4230 to master

**Comment by dexterurbane** [comment]
That's great - I really appreciate it. We're all fine too, it's pretty weird times but we're all healthy and well which is the main thing. Thanks again!

**Comment by hhijazi** [comment]
You're very welcome. For the unbalanced formulation check line 4143 in this file https://github.com/lanl-ansi/ODO/blob/master/examples/MINLP/Power/PowerNet.cpp
