### ISSUE TITLE
Ipopt=ON looks for libipopt.so in a wrong place: error: 'third_party/Install/ipopt/build/lib/libipopt.so' ... missing and no known rule to make it

### ISSUE THREAD

**Issue by yurivict** [coin-or/Gravity#92]
I already have ```ipopt``` installed at ```/usr/local/lib/libiopopt.so``` but it is looking in a subdirectory for some reason.

**Comment by hhijazi** [comment]
Gravity will look for the h files too: https://github.com/coin-or/Gravity/blob/master/cmake/FindIPOPT.cmake#L46
you can add more HINTS to this cmake file or just specify the root directory to Ipopt using `export IPOPT_ROOT_DIR="path"`

**Comment by yurivict** [comment]
No, ```IPOPT_ROOT_DIR``` doesn't work.

You should use:
```
pkg_check_modules(IPOPT REQUIRED IMPORTED_TARGET ipopt)
```

**Comment by hhijazi** [comment]
It has worked so far, I do realize you can use pkg_config, but I wouldn't consider this an "issue".

**Comment by yurivict** [comment]
No, it doesn't work with ```-DIPOPT_ROOT_DIR=/usr/local```:
```
-- Enable IPOPT
Looking for Ipopt in /usr/local
Cannot find Ipopt, will try pulling it from github.
-- Configuring done
-- Generating done
```

**Comment by yurivict** [comment]
I printed variables:
```
message(STATUS "IPOPT_INCLUDE_DIR=${IPOPT_INCLUDE_DIR}")
message(STATUS "IPOPT_LIBRARY=${IPOPT_LIBRARY}")
message(STATUS "IPOPT_LIBRARY2=${IPOPT_LIBRARY2}")
find_package_handle_standard_args(IPOPT DEFAULT_MSG IPOPT_LIBRARY IPOPT_LIBRARY2 IPOPT_INCLUDE_DIR)
```
It printed:
```
Looking for Ipopt in /disk-samsung/freebsd-ports/math/gravity/work/.build/third_party/Install/ipopt/build
-- IPOPT_INCLUDE_DIR=/usr/local/include/coin
-- IPOPT_LIBRARY=/usr/local/lib/libipopt.so
-- IPOPT_LIBRARY2=
Cannot find Ipopt, will try pulling it from github.
-- Configuring done
-- Generating done
-- Build files have been written to: /disk-samsung/freebsd-ports/math/gravity/work/.build
```
Both ```IPOPT_INCLUDE_DIR``` and ```IPOPT_LIBRARY``` are found, but it still says that it can't find ipopt.
