### ISSUE TITLE
Project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [coin-or/Gravity#94]

**Comment by hhijazi** [comment]
You will have to be a tiny bit more specific..

**Comment by yurivict** [comment]
```make install``` usually installs files like executables, libraries, header files so that they can be used, packaged, etc.

This is specified in ```CMakeLists.txt``` through ```install``` instructions: https://cmake.org/cmake/help/latest/command/install.html

**Comment by hhijazi** [comment]
Yes, binaries should appear under bin/Release and libgravity should appear under lib/ 
Check out the Travis run here: https://travis-ci.com/github/coin-or/Gravity/builds/225354079
What Cmake options did you use? you can maybe share the Cmake log.

**Comment by yurivict** [comment]
> Yes, binaries should appear under bin/Release and libgravity should appear under lib/

But they don't appear at a standard location in a stage directory.

You probably need to add:
```
install(TARGETS gravity DESTINATION lib)
install(DIRECTORY incude/gravity DESTINATION include)
```

**Comment by hhijazi** [comment]
This is specified in the Cmake file: https://github.com/coin-or/Gravity/blob/master/CMakeLists.txt#L292
And I've always seen the lib and executables appear where they're supposed to.

**Comment by yurivict** [comment]
They don't appear in a stage directory expected by all packaging systems, because there are no ```install``` instructions.

**Comment by hhijazi** [comment]
Thanks for pointing this out, I've added those install instructions here: https://github.com/coin-or/Gravity/commit/da941e9a51c49ea48ed585db7e5a710971cd8282 I also realized there was an issue in the FindIpopt.cmake file that crept in after trying to install Gravity on Windows, I believe it should now find your .so correctly.

**Comment by yurivict** [comment]
Now it installs and finds ipopt fine, thanks!
